### ISSUE TITLE
Able to set address to earn commission from collect module

### ISSUE THREAD

**Issue by bigint** [lens-protocol/core#109]
It would be great if it is able to set some percentage of commission fees to be earned for the frontend hosters

Example:

1% Referral fee
0.5% Commission fee (requesting this and it should be an optional parameter)
0.5% Protocol fee
98% Goes to the creator

cc @Zer0dot @donosonaumczuk @oneski

**Comment by donosonaumczuk** [comment]
Hey @bigint ! 

This is absolutely doable without any modifications in the protocol. It is just achievable by creating a collect module, same as the fee collect module, but that holds an extra logic to let you set an address and percentage for this "commission fee". Same could be done on reference and follow modules.

Maybe you can find someone in the Discord that wants to build it as part of its ETH Amsterdam Hackathon project, otherwise I can probably build it after it!

**Comment by donosonaumczuk** [comment]
Closing this for now, but we are keeping this on mind!
