### ISSUE TITLE
Allow user to follow from different profile `followFrom`

### ISSUE THREAD

**Issue by liamzebedee** [lens-protocol/core#110]
A lot of people have alts on Twitter. In Lens currently, to implement following from an alt, we need to make **another** Polygon transaction to call `LensHub.setDefaultProfile`. It seems very unnecessary when we could easily pass in the profile we intend to follow from, in the `follow` function.

Proposal: a function `followFrom` which allows you to follow from a different profile

```sol
    function followFrom(
        uint256 fromProfile,
        uint256[] calldata profileIds,
        bytes[] calldata followModuleDatas,
        address followNFTImpl,
        mapping(uint256 => DataTypes.ProfileStruct) storage _profileById,
        mapping(bytes32 => uint256) storage _profileIdByHandleHash
    ) external returns (uint256[] memory) {
       // Verify wallet is owner of fromProfile.
       // Proceed
```

**Comment by donosonaumczuk** [comment]
Hey @liamzebedee, follows are intentionally made by addresses instead of profiles by default. But profile-based interaction can be easily achieved by using custom modules, check out [ProfileFollowModule](https://github.com/aave/lens-protocol/blob/main/contracts/core/modules/follow/ProfileFollowModule.sol) which works as you suggested.

Same behavior can be added to collect or reference modules if wanted. Then is up to the indexer/API and UI how to use this information!

Please, let me know if this solves the issue.

**Comment by liamzebedee** [comment]
Hey Alan. I like the idea of anonymous follows from accounts being the base case, it's useful. IIRC the reason for adding the "defaultProfile" to the protocol was that being able to associate a profile follow to another profile was super useful too - important enough to add to the core protocol, and not a separate module.

**Comment by donosonaumczuk** [comment]
A delegation scheme has been under development, will share details soon, but it will allow to perform all core operations through a different address!
