### ISSUE TITLE
Proposal of decentralized storage

### ISSUE THREAD

**Issue by badkk** [lens-protocol/core#15]
I notice that Lens's publications has needs to integrate with dStorage, but I can't find from the code repo. 
> Publications have a ContentURI which points to the specific content the publication contains, this can point to text, an image, a video, or other arbitrary content stored on either a decentralized protocol such as [IPFS](https://ipfs.io/) or [Arweave](https://www.arweave.org/), or a centralized storage provider like AWS S3.

I was wondering if lens has any plan on integrating with IPFS, **I can definitely contribute code.**
I also have a **proposal of integrating with IPFS incentive layer - Crust**, that can help Lens' user easily permanently store the social media data in a totally decentralized way. Crust also be used in [aave-ui](https://github.com/aave/aave-ui/blob/master/.github/workflows/deploy.yml#L46-L52), [uniswap-interface](https://github.com/Uniswap/interface/blob/main/.github/workflows/release.yaml#L58-L64) and many NFTs/SocialFi/GamingFi projects.

**Comment by Zer0dot** [comment]
Sweet! Yeah would love to learn more. One benefit of Lens though is that it is unopinionated about what your content URI is. It's totally up to you-- but share more!

**Comment by donosonaumczuk** [comment]
As Zer0dot mentioned, Lens is storage agnostic, meaning you can host your publication's metadata in your preferred storage depending on your use case, it's up to each application. We already have different apps using IPFS, Arweave and even some using centralized storage too. I'm closing this but just because we want to keep issues open as signal of something to solve!
